title: XGBoost
description: Scalable and flexible gradient boosting
author: XGBoost Contributors
url: https://xgboost.ai
baseurl: ""

theme: minima
permalink: /:categories/:year/:month/:day/:title
highlighter: rouge
markdown: kramdown

header_pages:
  - about.md
  - blog.html
  - sponsors.md

minima:
  date_format: "%b %-d, %Y"

github_repository: dmlc/xgboost
twitter_username: XGBoostProject
show_excerpts: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .rvmrc
  - .rbenv-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - changelog.md
